import type { Dictionary } from "./dictionary";

export const en: Dictionary = {
  meta: {
    title: "MODA Barber Club — Crafted Cuts. Timeless Grooming.",
    description:
      "An upscale men's barbershop in Tel Aviv. Precision cuts, beard design and hot-towel shaves. Book your chair online in under a minute.",
  },
  common: {
    bookNow: "Book a chair",
    bookWithMe: "Book with me",
    viewServices: "View services",
    whatsapp: "WhatsApp",
    call: "Call the shop",
    navigate: "Get directions",
    close: "Close",
    back: "Back",
    next: "Continue",
    minutes: "min",
    from: "from",
    loading: "Loading",
    demoContent: "Demo content",
    languageName: "English",
    switchTo: "עברית",
    previousItems: "Show previous",
    nextItems: "Show next",
  },
  nav: {
    home: "Home",
    services: "Services",
    team: "Our team",
    gallery: "Gallery",
    experience: "The experience",
    reviews: "Reviews",
    visit: "Visit us",
    book: "Book",
    admin: "Admin",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  intro: {
    skip: "Skip",
    enter: "Enter",
    enterHint: "Press Enter to continue",
    label: "MODA Barber Club opening screen",
  },
  hero: {
    eyebrow: "Est. 2014 · Tel Aviv",
    titleLine1: "Crafted Cuts.",
    titleLine2: "Timeless Grooming.",
    lede: "A chair, a barber who knows your head, and twenty unhurried minutes. Precision cuts, beard design and hot-towel shaves — seven days a week, by appointment.",
    scroll: "Scroll",
    videoFallback: "The barbershop floor at night",
  },
  services: {
    eyebrow: "What we do",
    title: "Our services",
    lede: "Straightforward pricing, honest timings. Every appointment starts with a short consultation.",
    duration: "Duration",
    book: "Book this",
  },
  team: {
    eyebrow: "Who you'll meet",
    title: "Our barbers",
    lede: "Four barbers, four specialities. Pick the one you trust — or let us match you.",
    specialty: "Specialty",
    availability: "Usually in",
    previous: "Previous barber",
    nextBarber: "Next barber",
  },
  gallery: {
    eyebrow: "The work",
    title: "Gallery",
    lede: "Cuts, beards and the room they happen in.",
    all: "All",
    cuts: "Cuts",
    beards: "Beards",
    shop: "The shop",
    work: "At work",
    openImage: "Open image",
    previous: "Previous image",
    next: "Next image",
    counter: "{current} of {total}",
  },
  advantages: {
    eyebrow: "Why MODA",
    title: "Why men keep coming back",
    lede: "Nothing flashy. Just the things that make a haircut worth repeating.",
  },
  experience: {
    eyebrow: "Inside the shop",
    title: "The MODA experience",
    lede: "Warm light, dark wood and tools that are looked after. Take a look around before you sit down.",
    play: "Play video",
    pause: "Pause video",
  },
  testimonials: {
    eyebrow: "In their words",
    title: "What our clients say",
    lede: "A few words from the chair.",
    disclaimer:
      "Demo reviews — written for this template. Replace them with genuine client reviews before going live.",
    ratingLabel: "{rating} out of 5",
  },
  location: {
    eyebrow: "Come in",
    title: "Location & hours",
    hours: "Opening hours",
    closed: "Closed",
    address: "Address",
    contact: "Get in touch",
    mapNotice: "Map placeholder — connect the client's real location before launch.",
    today: "Today",
  },
  weekdays: {
    long: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    short: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
  months: [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
  ],
  booking: {
    eyebrow: "Book online",
    title: "Reserve your chair",
    lede: "Five short steps. No phone call, no waiting on hold.",
    steps: {
      service: "Service",
      barber: "Barber",
      time: "Date & time",
      details: "Your details",
      confirm: "Confirm",
    },
    stepCounter: "Step {current} of {total}",
    chooseService: "Choose a service",
    chooseBarber: "Choose your barber",
    anyBarber: "No preference",
    anyBarberNote: "We'll assign whoever is free at the time you pick.",
    chooseDate: "Pick a date",
    chooseTime: "Pick a time",
    noSlots: "No times left on this day",
    noSlotsHint: "Try the next day, or a different barber.",
    closedThatDay: "We're closed on this day.",
    loadingSlots: "Checking availability",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    yourDetails: "Your details",
    fullName: "Full name",
    fullNamePlaceholder: "e.g. David Cohen",
    phone: "Phone",
    phonePlaceholder: "050-123-4567",
    phoneHint: "Israeli mobile or landline. We only use it to confirm your appointment.",
    email: "Email",
    emailOptional: "optional",
    emailPlaceholder: "you@example.com",
    notes: "Anything we should know?",
    notesOptional: "optional",
    notesPlaceholder: "Scissors only, please — no clippers on top.",
    summary: "Your appointment",
    summaryService: "Service",
    summaryBarber: "Barber",
    summaryWhen: "When",
    summaryDuration: "Duration",
    summaryPrice: "Price",
    summaryName: "Name",
    summaryPhone: "Phone",
    confirmButton: "Confirm appointment",
    confirming: "Confirming",
    successTitle: "Your chair is booked",
    successBody: "We've saved your appointment. Show this number when you arrive.",
    confirmationNumber: "Confirmation",
    addToCalendar: "Add to calendar",
    bookAnother: "Book another appointment",
    errors: {
      nameRequired: "Please enter your name.",
      nameTooShort: "Please enter your full name.",
      phoneRequired: "Please enter a phone number.",
      phoneInvalid: "That doesn't look like an Israeli phone number.",
      emailInvalid: "Please check the email address.",
      slotTaken: "Sorry — that time was just taken. Please pick another.",
      generic: "Something went wrong. Please try again.",
      selectService: "Please choose a service first.",
      selectTime: "Please choose a time.",
    },
    demoNotice:
      "Demo mode: appointments are saved in this browser only. Connect Supabase to store them for real.",
  },
  admin: {
    title: "Appointments",
    subtitle: "Demo admin area",
    demoWarning:
      "DEMO ADMIN — no authentication. Anyone with this URL can see and change appointments. Add real auth before using this in production.",
    today: "Today",
    day: "Day",
    week: "Week",
    filterBarber: "Barber",
    allBarbers: "All barbers",
    noAppointments: "No appointments in this view.",
    client: "Client",
    service: "Service",
    barber: "Barber",
    time: "Time",
    status: "Status",
    actions: "Actions",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    noShow: "No-show",
    markCompleted: "Mark completed",
    markNoShow: "Mark no-show",
    cancel: "Cancel",
    cancelConfirm: "Cancel this appointment?",
    blockTime: "Block time",
    blockedTimes: "Blocked times",
    blockDate: "Date",
    blockFrom: "From",
    blockTo: "To",
    blockReason: "Reason",
    blockReasonPlaceholder: "Supplier delivery",
    addBlock: "Block it",
    removeBlock: "Remove",
    noBlocks: "Nothing blocked yet.",
    total: "Appointments",
    revenue: "Expected revenue",
    upcoming: "Upcoming",
    backToSite: "Back to site",
    storageMode: "Storage",
    storageDemo: "Browser (demo)",
    storageSupabase: "Supabase",
  },
  footer: {
    about: "About",
    explore: "Explore",
    hours: "Hours",
    contact: "Contact",
    follow: "Follow",
    privacy: "Privacy",
    accessibility: "Accessibility",
    terms: "Terms",
    rights: "All rights reserved.",
    builtNotice: "Demo site — content, imagery and reviews are placeholders.",
  },
};

export default en;
