import type { Dictionary } from "./dictionary";

export const he: Dictionary = {
  meta: {
    title: "MODA Barber Club — תספורות מדויקות, טיפוח קלאסי",
    description:
      "מספרת גברים יוקרתית בתל אביב. תספורות מדויקות, עיצוב זקן וגילוח מגבת חמה. קביעת תור אונליין בפחות מדקה.",
  },
  common: {
    bookNow: "קביעת תור",
    bookWithMe: "קבעו איתי",
    viewServices: "לשירותים",
    whatsapp: "וואטסאפ",
    call: "התקשרו אלינו",
    navigate: "נווטו אלינו",
    close: "סגירה",
    back: "חזרה",
    next: "המשך",
    minutes: "דק'",
    from: "החל מ-",
    loading: "טוען",
    demoContent: "תוכן דמו",
    languageName: "עברית",
    switchTo: "English",
  },
  nav: {
    home: "בית",
    services: "שירותים",
    team: "הצוות",
    gallery: "גלריה",
    experience: "החוויה",
    reviews: "ביקורות",
    visit: "מיקום",
    book: "תור",
    admin: "ניהול",
    openMenu: "פתיחת תפריט",
    closeMenu: "סגירת תפריט",
  },
  intro: {
    skip: "דילוג",
    enter: "כניסה",
    enterHint: "הקישו Enter להמשך",
    label: "מסך הפתיחה של MODA Barber Club",
  },
  hero: {
    eyebrow: "נוסדה 2014 · תל אביב",
    titleLine1: "תספורות מדויקות.",
    titleLine2: "טיפוח שלא יוצא מהאופנה.",
    lede: "כיסא, ספר שמכיר את הראש שלכם, ועשרים דקות בלי למהר. תספורות מדויקות, עיצוב זקן וגילוח מגבת חמה — בתיאום מראש.",
    scroll: "גללו",
    videoFallback: "חלל המספרה בשעות הערב",
  },
  services: {
    eyebrow: "מה אנחנו עושים",
    title: "השירותים שלנו",
    lede: "מחירים ברורים וזמנים אמיתיים. כל תור נפתח בייעוץ קצר.",
    duration: "משך",
    book: "קביעת השירות",
  },
  team: {
    eyebrow: "מי מחכה לכם",
    title: "הספרים שלנו",
    lede: "ארבעה ספרים, ארבע התמחויות. בחרו את מי שאתם סומכים עליו — או תנו לנו להתאים.",
    specialty: "התמחות",
    availability: "בדרך כלל נמצא",
    previous: "הספר הקודם",
    nextBarber: "הספר הבא",
  },
  gallery: {
    eyebrow: "העבודה",
    title: "גלריה",
    lede: "תספורות, זקנים והחלל שבו הכול קורה.",
    all: "הכול",
    cuts: "תספורות",
    beards: "זקנים",
    shop: "המספרה",
    work: "בעבודה",
    openImage: "פתיחת התמונה",
    previous: "התמונה הקודמת",
    next: "התמונה הבאה",
    counter: "{current} מתוך {total}",
  },
  advantages: {
    eyebrow: "למה MODA",
    title: "למה חוזרים אלינו",
    lede: "בלי גימיקים. רק הדברים שהופכים תספורת לכזו ששווה לחזור אליה.",
  },
  experience: {
    eyebrow: "בתוך המספרה",
    title: "החוויה ב-MODA",
    lede: "תאורה חמה, עץ כהה וכלים שמטפלים בהם. הציצו לפני שאתם מתיישבים.",
    play: "הפעלת הסרטון",
    pause: "עצירת הסרטון",
  },
  testimonials: {
    eyebrow: "במילים שלהם",
    title: "מה הלקוחות אומרים",
    lede: "כמה מילים מהכיסא.",
    disclaimer:
      "ביקורות דמו — נכתבו עבור התבנית הזאת. יש להחליף אותן בביקורות אמיתיות לפני עלייה לאוויר.",
    ratingLabel: "{rating} מתוך 5",
  },
  location: {
    eyebrow: "בואו אלינו",
    title: "מיקום ושעות",
    hours: "שעות פעילות",
    closed: "סגור",
    address: "כתובת",
    contact: "יצירת קשר",
    mapNotice: "מפה זמנית — יש לחבר את המיקום האמיתי של הלקוח לפני העלייה לאוויר.",
    today: "היום",
  },
  weekdays: {
    long: ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שבת"],
    short: ["א׳", "ב׳", "ג׳", "ד׳", "ה׳", "ו׳", "ש׳"],
  },
  months: [
    "ינואר", "פברואר", "מרץ", "אפריל", "מאי", "יוני",
    "יולי", "אוגוסט", "ספטמבר", "אוקטובר", "נובמבר", "דצמבר",
  ],
  booking: {
    eyebrow: "קביעת תור",
    title: "שמרו את הכיסא שלכם",
    lede: "חמישה שלבים קצרים. בלי טלפון ובלי המתנה על הקו.",
    steps: {
      service: "שירות",
      barber: "ספר",
      time: "תאריך ושעה",
      details: "הפרטים שלכם",
      confirm: "אישור",
    },
    stepCounter: "שלב {current} מתוך {total}",
    chooseService: "בחרו שירות",
    chooseBarber: "בחרו ספר",
    anyBarber: "לא משנה לי",
    anyBarberNote: "נשבץ את מי שפנוי בשעה שתבחרו.",
    chooseDate: "בחרו תאריך",
    chooseTime: "בחרו שעה",
    noSlots: "אין שעות פנויות ביום הזה",
    noSlotsHint: "נסו את היום הבא, או ספר אחר.",
    closedThatDay: "אנחנו סגורים ביום הזה.",
    loadingSlots: "בודקים זמינות",
    morning: "בוקר",
    afternoon: "צהריים",
    evening: "ערב",
    yourDetails: "הפרטים שלכם",
    fullName: "שם מלא",
    fullNamePlaceholder: "לדוגמה: דוד כהן",
    phone: "טלפון",
    phonePlaceholder: "050-123-4567",
    phoneHint: "נייד או קו נייח בישראל. נשתמש בו רק לאישור התור.",
    email: "אימייל",
    emailOptional: "לא חובה",
    emailPlaceholder: "you@example.com",
    notes: "משהו שכדאי שנדע?",
    notesOptional: "לא חובה",
    notesPlaceholder: "רק מספריים בבקשה, בלי מכונה למעלה.",
    summary: "התור שלכם",
    summaryService: "שירות",
    summaryBarber: "ספר",
    summaryWhen: "מתי",
    summaryDuration: "משך",
    summaryPrice: "מחיר",
    summaryName: "שם",
    summaryPhone: "טלפון",
    confirmButton: "אישור התור",
    confirming: "מאשרים",
    successTitle: "הכיסא שלכם שמור",
    successBody: "התור נשמר. הציגו את המספר הזה כשאתם מגיעים.",
    confirmationNumber: "מספר הזמנה",
    addToCalendar: "הוספה ליומן",
    bookAnother: "קביעת תור נוסף",
    errors: {
      nameRequired: "נא להזין שם.",
      nameTooShort: "נא להזין שם מלא.",
      phoneRequired: "נא להזין מספר טלפון.",
      phoneInvalid: "המספר הזה לא נראה כמו מספר טלפון ישראלי.",
      emailInvalid: "נא לבדוק את כתובת האימייל.",
      slotTaken: "מצטערים — השעה הזאת נתפסה הרגע. בחרו שעה אחרת.",
      generic: "משהו השתבש. נסו שוב.",
      selectService: "נא לבחור שירות תחילה.",
      selectTime: "נא לבחור שעה.",
    },
    demoNotice:
      "מצב דמו: התורים נשמרים בדפדפן הזה בלבד. חברו Supabase כדי לשמור אותם באמת.",
  },
  admin: {
    title: "תורים",
    subtitle: "אזור ניהול לדמו",
    demoWarning:
      "אזור ניהול לדמו — ללא הזדהות. כל מי שיש לו את הכתובת יכול לראות ולשנות תורים. יש להוסיף אימות אמיתי לפני שימוש בפרודקשן.",
    today: "היום",
    day: "יומי",
    week: "שבועי",
    filterBarber: "ספר",
    allBarbers: "כל הספרים",
    noAppointments: "אין תורים בתצוגה הזאת.",
    client: "לקוח",
    service: "שירות",
    barber: "ספר",
    time: "שעה",
    status: "סטטוס",
    actions: "פעולות",
    confirmed: "מאושר",
    completed: "הושלם",
    cancelled: "בוטל",
    noShow: "לא הגיע",
    markCompleted: "סימון כהושלם",
    markNoShow: "סימון כלא הגיע",
    cancel: "ביטול",
    cancelConfirm: "לבטל את התור הזה?",
    blockTime: "חסימת שעות",
    blockedTimes: "שעות חסומות",
    blockDate: "תאריך",
    blockFrom: "משעה",
    blockTo: "עד שעה",
    blockReason: "סיבה",
    blockReasonPlaceholder: "קבלת סחורה",
    addBlock: "חסימה",
    removeBlock: "הסרה",
    noBlocks: "אין עדיין שעות חסומות.",
    total: "תורים",
    revenue: "הכנסה צפויה",
    upcoming: "הקרובים",
    backToSite: "חזרה לאתר",
    storageMode: "אחסון",
    storageDemo: "דפדפן (דמו)",
    storageSupabase: "Supabase",
  },
  footer: {
    about: "אודות",
    explore: "ניווט",
    hours: "שעות",
    contact: "צור קשר",
    follow: "עקבו",
    privacy: "פרטיות",
    accessibility: "נגישות",
    terms: "תנאים",
    rights: "כל הזכויות שמורות.",
    builtNotice: "אתר דמו — התוכן, התמונות והביקורות הם זמניים.",
  },
};

export default he;
